### ISSUE TITLE
More responsive to scroll bar

### ISSUE THREAD

**Issue by rickyvetter** [justinwoo/cycle-scroll-table#1]
This is really cool - just curious why is there a white flash/loading when I scroll with my mouse, but no flash at all when I use the bar (even when I'm scrolling much further with the bar)?

![scroll](https://cloud.githubusercontent.com/assets/4370652/8492192/56303cb2-2114-11e5-88c9-1afa04dcc00e.gif)

**Comment by justinwoo** [comment]
i think mouse scroll events are throttled by chrome or something, this happens in every version of this scroll table in chrome, but i haven't seen this happen in IE or firefox (yet)

![CHROME!!!](http://share.gifyoutube.com/v1ZeZ3.gif)

**Comment by rickyvetter** [comment]
interesting. good to know! I'm gonna try cycle out for some personal projects. looks like a lot of fun. thanks for the example :)
