### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by PhiLhoSoft** [justinwoo/cycle-scroll-table#3]
I tried the demo. I see a "nice" table with a scroll bar. I scroll to the middle. I see a blank area instead of more rows.

Suspecting it was working for you, I switched from Firefox (latest, ie. 38) to Chrome (latest too, 43) and, surprise! it works...

So you might need to spend another hour (or probably much less if FB isn't in the way... :smile:) to fix that...

**Comment by justinwoo** [comment]
oh, looks like i get `TypeError: e.srcElement is undefined` in firefox. i'll have to dig into it sometime...

**Comment by justinwoo** [comment]
should work in FF now. works for me.

oops, probably should've known not to just use whatever chrome had available in the console.

**Comment by PhiLhoSoft** [comment]
I can confirm it works for me now... :smile:  That was fast!

(Side note: the title of the issue was a parody of most issues made by newbies / end users. Usually, I made more descriptive subjects...)
